In [1]:
# A: 선택된 셀 위에 새로운 셀 추가
# B: 선택된 셀 아래에 새로운 셀 추가
# X: 선택된 셀 잘라내기
# C: 선택된 셀 복사
# V: 선택된 셀 아래에 붙여넣기
# Shift + V: 선택된 셀 위에 붙여넣기
# D, D: 선택된 셀 삭제 (D를 두 번 누르세요)
# Z: 셀 삭제를 취소
# Y: 선택된 셀을 코드 셀로 변경
# M: 선택된 셀을 마크다운 셀로 변경
# R: 선택된 셀을 Raw 셀로 변경
# Shift + Enter: 선택된 셀 실행 후 다음 셀로 이동
# Ctrl + Enter: 선택된 셀 실행 (다음 셀로 이동하지 않음)
# Alt + Enter: 선택된 셀 실행 후 아래에 새로운 셀 추가

In [2]:
import numpy as np

In [3]:
my_list = [1,2,3]

In [4]:
type(my_list)

list

In [5]:
np.array(my_list)

array([1, 2, 3])

In [6]:
arr = np.array(my_list)

In [7]:
arr

array([1, 2, 3])

In [8]:
my_list = [[1,2,3],[4,5,6],[7,8,9]]

In [9]:
my_list

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [11]:
my_matrix = np.array(my_list)

In [12]:
my_matrix.shape

(3, 3)

In [13]:
my_new_matrix = np.array(my_list)

In [ ]:
my_new_matrix.

In [14]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [16]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [17]:
type(0.)

float

In [18]:
np.zeros((4,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [19]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [20]:
np.ones((5,5)) + 4

array([[5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.]])

In [21]:
np.ones(4) * 100

array([100., 100., 100., 100.])

In [23]:
[1,1,1,1] * 100

[1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,


In [24]:
[1,1,1,1] + 10

TypeError: can only concatenate list (not "int") to list

In [25]:
np.ones(4) / 100

array([0.01, 0.01, 0.01, 0.01])

In [26]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [28]:
np.linspace(0,10,20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [29]:
len(np.linspace(0,10,20))

20

In [30]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [31]:
np.random.rand(4)

array([0.65882014, 0.94540559, 0.39710385, 0.96381307])

In [37]:
# 0 ~ 1 사이의 난수
np.random.rand(5,5)

array([[0.63623636, 0.91609248, 0.54280431, 0.05918373, 0.50353419],
       [0.3611596 , 0.36597255, 0.78336923, 0.36900477, 0.27176673],
       [0.62546119, 0.76887139, 0.31556188, 0.68490049, 0.81545216],
       [0.22817556, 0.09377483, 0.63235928, 0.29303298, 0.69141526],
       [0.42523142, 0.57362235, 0.96663674, 0.07516616, 0.59545742]])

In [33]:
# 표준 정규 분포를 따르는 난수
np.random.randn(2)

array([-0.78981117,  0.5104303 ])

In [35]:
# 평균, 표준편차, 데이터 개수
np.random.normal(0,1,10)

array([-0.1341691 , -1.67892589,  0.89332837, -0.09526279, -0.96596335,
        0.15874231,  0.04697054, -0.02496601, -0.1893323 ,  0.22806062])

In [36]:
# 1 ~ 100 사이의 정수 난수 10개 (균일 분포)
np.random.randint(1,100,10)

array([90,  8, 94, 98, 97, 18, 43, 85,  1, 98])

In [43]:
# 무작위 함수 결과 고정 (시드 값 고정): 같은 셀에 함께 존재해야 한다.
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [44]:
np.random.rand(4)

array([0.15601864, 0.15599452, 0.05808361, 0.86617615])

In [46]:
arr = np.arange(25)

In [47]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [48]:
ranarr = np.random.randint(0,50,10)

In [50]:
ranarr

array([35, 39, 23,  2, 21,  1, 23, 43, 29, 37])

In [51]:
arr.shape

(25,)

In [52]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [53]:
arr.reshape(5,3)

ValueError: cannot reshape array of size 25 into shape (5,3)

In [54]:
ranarr.max()

43

In [55]:
ranarr.min()

1

In [56]:
ranarr

array([35, 39, 23,  2, 21,  1, 23, 43, 29, 37])

In [57]:
# find index location
ranarr.argmax()

7

In [58]:
ranarr.argmin()

5

In [59]:
# 데이터의 타입, 데이터를 표현하기 위해 사용하는 저장 공간의 크기(bit)
ranarr.dtype

dtype('int32')